# Generated by Django 5.2 on 2025-04-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Питання'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Правильна відповідь 1'), (2, 'Правильна відповідь 2'), (3, 'Правильна відповідь 3'), (4, 'Правильна відповідь 4')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
